In [36]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [37]:
data=pd.read_csv("Movie_Preference_Dataset.csv")
data

,Customer,Action,Horror,Comedy,Romance,SciFi,Animation,Thriller,Rating(1-5),Likes Movie
0,C1,0,1,0,0,0,0,0,2,No
1,C2,0,0,1,0,0,1,1,3,Yes
2,C3,1,0,1,1,0,0,0,2,Yes
3,C4,0,1,1,1,0,1,0,5,Yes
4,C5,0,1,0,1,1,1,0,1,No
...,...,...,...,...,...,...,...,...,...,...
495,C496,0,0,1,1,1,0,1,3,Yes
496,C497,0,0,0,0,1,0,0,3,No
497,C498,0,0,0,0,0,0,0,4,No
498,C499,0,1,0,1,1,1,1,1,Yes


In [38]:
print(data.head())

  Customer  Action  Horror  Comedy  Romance  SciFi  Animation  Thriller  \
0       C1       0       1       0        0      0          0         0   
1       C2       0       0       1        0      0          1         1   
2       C3       1       0       1        1      0          0         0   
3       C4       0       1       1        1      0          1         0   
4       C5       0       1       0        1      1          1         0   

   Rating(1-5) Likes Movie  
0            2          No  
1            3         Yes  
2            2         Yes  
3            5         Yes  
4            1          No  


In [41]:
print(data.isnull().sum())

Customer       0
Action         0
Horror         0
Comedy         0
Romance        0
SciFi          0
Animation      0
Thriller       0
Rating(1-5)    0
Likes Movie    0
dtype: int64


In [42]:
data.dropna(inplace=True)
data.drop_duplicates(inplace=True)

In [43]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer     500 non-null    str  
 1   Action       500 non-null    int64
 2   Horror       500 non-null    int64
 3   Comedy       500 non-null    int64
 4   Romance      500 non-null    int64
 5   SciFi        500 non-null    int64
 6   Animation    500 non-null    int64
 7   Thriller     500 non-null    int64
 8   Rating(1-5)  500 non-null    int64
 9   Likes Movie  500 non-null    str  
dtypes: int64(8), str(2)
memory usage: 35.2 KB
None


In [44]:
action=data["Action"]
horror=data["Horror"]
comedy=data ["Comedy"]
romance=data["Romance"]
scifi=data["SciFi"]
animation=data["Animation"]
thriller=data["Thriller"]
x=np.column_stack([action,horror,comedy,romance,scifi,animation,thriller])
x

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 0]], shape=(500, 7), dtype=int64)

In [45]:
print(x.shape)

(500, 7)


In [46]:
le = LabelEncoder()
y=le.fit_transform(data["Likes Movie"])
print(le.classes_)
y

['No' 'Yes']


array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,

In [47]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,test_size=0.2,random_state=42
)

In [48]:
model=BernoulliNB()
model.fit(x_train, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"binarize binarize: float or None, default=0.0Threshold for binarizing (mapping to booleans) of sample features.If None, input is presumed to already consist of binary vectors.",0.0
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [60]:
import numpy as np
Action = int(input("Enter Action movie (1-Yes, 0-No): "))
Horror = int(input("Enter Horror movie (1-Yes, 0-No): "))
Comedy = int(input("Enter Comedy movie (1-Yes, 0-No): "))
Romance = int(input("Enter Romance movie (1-Yes, 0-No): "))
SciFi = int(input("Enter SciFi movie (1-Yes, 0-No): "))
Animation = int(input("Enter Animation movie (1-Yes, 0-No): "))
Thriller = int(input("Enter Thriller movie (1-Yes, 0-No): "))

new_movie = np.array([
    Action,
    Horror,
    Comedy,
    Romance,
    SciFi,
    Animation,
    Thriller
]).reshape(1, -1)

prediction = model.predict(new_movie)

print("Prediction:", le.inverse_transform(prediction)[0])

Enter Action movie (1-Yes, 0-No):  1
Enter Horror movie (1-Yes, 0-No):  0
Enter Comedy movie (1-Yes, 0-No):  1
Enter Romance movie (1-Yes, 0-No):  1
Enter SciFi movie (1-Yes, 0-No):  0
Enter Animation movie (1-Yes, 0-No):  0
Enter Thriller movie (1-Yes, 0-No):  1


Prediction: Yes


In [51]:

y_pred = model.predict(x_test)
print(y_pred)
print(le.inverse_transform(y_pred))

[0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1
 1 1 0 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1 1 0
 1 1 1 0 0 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1]
['No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes']


In [52]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[23 13]
 [ 5 59]]


In [54]:
f1=f1_score(y_test,y_pred)
f1

0.8676470588235294

In [55]:
recall=recall_score(y_test,y_pred)
recall

0.921875

In [56]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.82
